export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const FETCH_HISTORY_START='FETCH_HISTORY_START'
export const FETCH_HISTORY_SUCCESS='FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_ERROR='FETCH_HISTORY_ERROR'
export const AUTH_LOGOUT='AUTH_LOGOUT'
export const AUTH_SUCCESS='AUTH_SUCCESS'
